# TODO(dchu): we should exclude names that match either "__.*" and "_[A-Z].*".
from typing import Set


# Names reserved by the C standard library
STDIO_H_NAMES: Set[str] = {
    # According to https://www.tutorialspoint.com/c_standard_library/stdio_h.htm
    # Types
    "size_t",
    "FILE",
    "fpost_t",
    # Macros
    "NULL",
    "_IOFBF",
    "_IOLBF",
    "_IONBF",
    "BUFSIZ",
    "EOF",
    "FOPEN_MAX",
    "FILENAME_MAX",
    "L_tmpnam",
    "SEEK_CUR",
    "SEEK_END",
    "SEEK_SET",
    "TMP_MAX",
    "stderr",
    "stdin",
    "stdout",
    # Functions
    "fclose",
    "clearerr",
    "feof",
    "ferror",
    "fflush",
    "fgetpos",
    "fopen",
    "fread",
    "freopen",
    "fseek",
    "fsetpos",
    "ftell",
    "fwrite",
    "remove",
    "rename",
    "rewind",
    "setbuf",
    "setvbuf",
    "tmpfile",
    "tmpnam",
    "fprintf",
    "printf",
    "sprintf",
    "vfprintf",
    "vprintf",
    "vsprintf",
    "fscanf",
    "scanf",
    "sscanf",
    "fgetc",
    "fgets",
    "fputc",
    "fputs",
    "getc",
    "getchar",
    "gets",  # NOTE: very dangerous function!
    "putc",
    "putchar",
    "puts",
    "ungetc",
    "perror",
}

STDLIB_H_NAMES: Set[str] = {
    # According to https://www.tutorialspoint.com/c_standard_library/stdlib_h.htm
    # Types
    "size_t",
    "wchar_t",
    "div_t",
    "ldiv_t",
    # Macros
    "NULL",
    "EXIT_FAILURE",
    "EXIT_SUCCESS",
    "RAND_MAX",
    "MB_CUR_MAX",
    # Functions
    "atof",
    "atoi",
    "atol",
    "strtod",
    "strtol",
    "strtoul",
    "calloc",
    "free",
    "malloc",
    "realloc",
    "abort",
    "atexit",
    "exit",
    "getenv",
    "system",
    "bsearch",
    "qsort",
    "abs",
    "div",
    "labs",
    "ldiv",
    "rand",
    "srand",
    "mblen",
    "mbstowcs",
    "mbtowc",
    "wcstombs",
    "wctomb",
}

# TODO(dchu): include full set of C standard library names in here.
C_STANDARD_LIBRARY_NAMES: Set[str] = set().union(STDIO_H_NAMES, STDLIB_H_NAMES)
